name: dcdg
description: A tool to automatically generate class diagrams (like UML) from a Dart package.
version: 1.3.0
homepage: https://github.com/glesica/dcdg.dart
author: George Lesica <george@lesica.com>
executables:
  dcdg:

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  analyzer: ^0.36.0
  args: ^1.5.1
  meta: ^1.1.7
  path: ^1.4.1

dev_dependencies:
  mockito: ^4.0.0
  pedantic: ^1.0.0
  test: ^1.0.0

