name: dartagram
description: A tool to generate a PlantUML diagram from a Dart package.
version: 1.0.0
homepage: https://github.com/georgelesica-wf/dartagram
author: George Lesica <george.lesica@workiva.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  analyzer: any
  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
