name: dcdg
description: A tool to automatically generate class diagrams (like UML) from a Dart package.
version: 2.0.1
homepage: https://github.com/glesica/dcdg.dart
author: George Lesica <george@lesica.com>
executables:
  dcdg:

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  analyzer: ^0.36.0
  args: ^1.5.0
  meta: ^1.0.0
  path: ^1.4.0

dev_dependencies:
  mockito: ^4.0.0
  pedantic: ^1.0.0
  test: ^1.0.0

